name: bitholla_assesment
description: New Cryptocurrency demo app .


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #state management
  get: ^4.6.1

  #utils
  shared_preferences: ^2.0.12
  sizer: ^2.0.15
  flutter_svg: ^1.0.1
  syncfusion_flutter_charts: ^19.4.42
  intl: ^0.17.0
  shimmer: ^2.0.0

  #networking
  vexana: ^2.5.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/fonts/
  
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
